### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by honzavaclavik** [planette/nutella-project#139]
`composer create-project planette/forest-project` fails
 
![image](https://user-images.githubusercontent.com/12621450/98154113-8d73ab00-1ed4-11eb-816e-bfbc1db6830c.png)

Is any stable planned?

**Comment by f3l1x** [comment]
Hi @honzavaclavik. This is example project, there will be no releases. Just install this project and make an application on top of it.

```
composer create-project -s dev planette/nutella-project acme
```
